# -*- coding: utf-8 -*-
"""canny-edge-detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FbNIgXRDj1eNiW0l-FvP3dxYtHgzAA3
"""

# STEP 1: Upload image
from google.colab import files
uploaded = files.upload()

# STEP 2: Import libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt

# STEP 3: Read image
image_path = list(uploaded.keys())[0]
img = cv2.imread(image_path)

# Convert BGR to RGB
rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Convert RGB to Grayscale
gray = cv2.cvtColor(rgb, cv2.COLOR_RGB2GRAY)

# STEP 4: Apply Gaussian Blur (noise removal)
blur = cv2.GaussianBlur(gray, (5,5), 0)

# STEP 5: Apply Canny Edge Detection
edges = cv2.Canny(blur, 50, 150)

# STEP 6: Display results
plt.figure(figsize=(12,6))

plt.subplot(1,3,1)
plt.imshow(rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(gray, cmap='gray')
plt.title("Grayscale Image")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(edges, cmap='gray')
plt.title("Canny Edge Detection")
plt.axis("off")

plt.show()