# -*- coding: utf-8 -*-
"""imagedblur.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJ_PZsgqO4xpke-mHFi-m5N5ruRbl2Vc
"""

# Image Deblurring using Wiener Filter
# Google Colab Compatible

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from scipy.signal import convolve2d
from skimage.restoration import wiener

# Upload image
uploaded = files.upload()

# Get uploaded filename
image_path = list(uploaded.keys())[0]

# Read image in grayscale
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

# Display original image
plt.figure(figsize=(6,6))
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis('off')
plt.show()

# Step 1: Create blur kernel (Gaussian blur simulation)
kernel_size = 15
sigma = 3

kernel_1d = cv2.getGaussianKernel(kernel_size, sigma)
kernel = kernel_1d @ kernel_1d.T

# Apply blur
blurred = cv2.filter2D(img, -1, kernel)

plt.figure(figsize=(6,6))
plt.imshow(blurred, cmap='gray')
plt.title("Blurred Image")
plt.axis('off')
plt.show()

# Step 2: Recover image using Wiener filter
recovered = wiener(blurred, kernel, balance=0.1)

plt.figure(figsize=(6,6))
plt.imshow(recovered, cmap='gray')
plt.title("Recovered (Deblurred) Image")
plt.axis('off')
plt.show()

# Compare all images
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(img, cmap='gray')
plt.title("Original")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(blurred, cmap='gray')
plt.title("Blurred")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(recovered, cmap='gray')
plt.title("Recovered")
plt.axis('off')

plt.show()