# -*- coding: utf-8 -*-
"""rgb converter.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qpx_F3_DnEgTDMEi-oYiAyAfc5Vpqs2-
"""

# STEP 1: Upload Image
from google.colab import files
uploaded = files.upload()

# STEP 2: Import Libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt

# STEP 3: Read Uploaded Image
image_path = list(uploaded.keys())[0]

# Read image using OpenCV (BGR format)
image = cv2.imread(image_path)

# Convert BGR to RGB
rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Display Original Image
plt.figure(figsize=(6,6))
plt.imshow(rgb_image)
plt.title("Original RGB Image")
plt.axis("off")
plt.show()

# STEP 4: Convert RGB to Grayscale
gray_opencv = cv2.cvtColor(rgb_image, cv2.COLOR_RGB2GRAY)

plt.figure(figsize=(6,6))
plt.imshow(gray_opencv, cmap='gray')
plt.title("Grayscale Image (OpenCV)")
plt.axis("off")
plt.show()